services:
  - type: web
    name: stock-predictor
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_SIGNALS_CHANNEL_ID
        sync: false
      - key: DISCORD_TRADES_CHANNEL_ID
        sync: false
      - key: DISCORD_HEARTBEAT_CHANNEL_ID
        sync: false
      - key: CHECK_SECRET
        sync: false
      - key: DISCORD_PUBLIC_KEY
        sync: false
